apiVersion: kpack.io/v1alpha1
kind: Image
metadata:
  name: petclinic
spec:
  builder:
    kind: ClusterBuilder
    name: default
  cacheSize: 2G
  imageTaggingStrategy: BuildNumber
  serviceAccount: default
  source:
    git:
      revision: main
      url: https://github.com/JasonMorgan/spring-petclinic
  successBuildHistoryLimit: 10
  tag: jasonmorgan/petclinic
